[package]
name = "realworld-tide-sqlite-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.16.0"
log = "0.4"
env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.5.10", features = [ "runtime-async-std-native-tls", "sqlite", "chrono" ] }
async-std = { version = "1.10.0", features = [ "attributes" ] }
async-trait = "0.1.52"
validator = { version = "0.14.0", features = ["derive"] }
http-types = "2.12.0"
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"
chrono = "0.4.19"
slugify = "0.1.0"
once_cell = "1.9.0"
scrypt = "0.8.1"